refactor: workflow.yml to disable E2E tests

diff --git a/.github/workflows/workflow.yml b/.github/workflows/workflow.yml
--- a/.github/workflows/workflow.yml
+++ b/.github/workflows/workflow.yml
@@ -89,53 +89,53 @@ jobs:
       - name: Run Tests
         run: yarn nx run-many --target=test --all
 
-  e2e-tests:
-    name: E2E Tests 🚦
-    runs-on: ubuntu-latest
-    needs: setup
-    steps:
-      - name: Checkout Repository
-        uses: actions/checkout@v4
-        with:
-          # fetch-depth gives the complete git history which is needed for nx.
-          fetch-depth: 0
-          ref: ${{ github.event.pull_request.head.sha }}
+  # e2e-tests:
+  #   name: E2E Tests 🚦
+  #   runs-on: ubuntu-latest
+  #   needs: setup
+  #   steps:
+  #     - name: Checkout Repository
+  #       uses: actions/checkout@v4
+  #       with:
+  #         # fetch-depth gives the complete git history which is needed for nx.
+  #         fetch-depth: 0
+  #         ref: ${{ github.event.pull_request.head.sha }}
 
-      - name: Setup Node.js
-        uses: actions/setup-node@v4
-        with:
-          node-version-file: '.nvmrc'
+  #     - name: Setup Node.js
+  #       uses: actions/setup-node@v4
+  #       with:
+  #         node-version-file: '.nvmrc'
 
-      - name: Restore Cache node_modules and Cypress binary
-        uses: actions/cache@v4
-        with:
-          path: |
-            node_modules
-            ~/.cache/Cypress
-          key: ${{ runner.os }}-node-modules-and-cypress-${{ hashFiles('yarn.lock') }}
+  #     - name: Restore Cache node_modules and Cypress binary
+  #       uses: actions/cache@v4
+  #       with:
+  #         path: |
+  #           node_modules
+  #           ~/.cache/Cypress
+  #         key: ${{ runner.os }}-node-modules-and-cypress-${{ hashFiles('yarn.lock') }}
 
-      - name: Install Dependencies
-        if: steps.cache.outputs.cache-hit != 'true'
-        run: yarn install --frozen-lockfile
+  #     - name: Install Dependencies
+  #       if: steps.cache.outputs.cache-hit != 'true'
+  #       run: yarn install --frozen-lockfile
 
-      - name: Verify Cypress Binary
-        run: npx cypress verify
+  #     - name: Verify Cypress Binary
+  #       run: npx cypress verify
 
-      - name: Start Server
-        run: npx nx run backend:serve &
-        shell: bash
+  #     - name: Start Server
+  #       run: npx nx run backend:serve &
+  #       shell: bash
 
-      - name: Wait for Server
-        run: |
-          while ! nc -z localhost 3000; do sleep 1; done
+  #     - name: Wait for Server
+  #       run: |
+  #         while ! nc -z localhost 3000; do sleep 1; done
 
-      - name: Run E2E Tests
-        run: yarn nx run-many --target=e2e --all
+  #     - name: Run E2E Tests
+  #       run: yarn nx run-many --target=e2e --all
 
-      - name: Shutdown Server
-        if: always() # Ensures this step runs even if the previous step fails
-        run: kill $(jobs -p) || true
-        shell: bash
+  #     - name: Shutdown Server
+  #       if: always() # Ensures this step runs even if the previous step fails
+  #       run: kill $(jobs -p) || true
+  #       shell: bash
 
   lint:
     name: Lint 🎨
